# Generated by Django 4.2.5 on 2023-09-28 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 42, 13, 950155)),
        ),
    ]
