# Generated by Django 4.2.5 on 2023-09-28 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 21, 13, 43, 145391)),
        ),
    ]
