# Generated by Django 4.2.5 on 2023-09-28 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='content3',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='content4',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title2',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='title3',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 42, 13, 965778)),
        ),
    ]
