# Generated by Django 4.2.5 on 2023-09-28 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_content2_blog_content3_blog_content4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 21, 13, 43, 160992)),
        ),
    ]
